branches:
    only:
        - devel
dist: xenial
addons:
  apt:
    packages:
    - hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  verbose: true
  local-dir: public
  on:
    branch: master

script: |
  hugo
  