baseURL = "https://www.cogitri.dev"
languageCode = "en-gb"
title = "Cogitri's blog"
theme = "github-style"
paginatePath = ""

[params]
	author = "Rasmus Thomsen"
	description = "Cogitri's Blog"
	github = "Cogitri"
	avatar = "https://avatars1.githubusercontent.com/u/8766773?s=460&v=4"
	email = "oss@cogitri.dev"
